version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: loginapp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: UserDB
      MYSQL_USER: devops
      MYSQL_PASSWORD: devops12345
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro

  app:
    image: srdevop/java-login-app:v2
    container_name: loginapp_web
    depends_on:
      - db
    environment:
      DB_USERNAME: devops
      DB_PASSWORD: devops12345
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8080:8080"

volumes:
  db_data:
